INSERT INTO workers (id, first_name, last_name, is_active)
VALUES (nextval('worker_id_seq'),
        'Mihajlo',
        'Subotić',
        true),
       (nextval('worker_id_seq'),
        'Milan',
        'Vujović',
        true),
       (nextval('worker_id_seq'),
        'Milimir',
        'Antunović',
        true),
       (nextval('worker_id_seq'),
        'Rodoljub',
        'Bratić',
        true),
       (nextval('worker_id_seq'),
        'Radovan',
        'Škiljević',
        true),
       (nextval('worker_id_seq'),
        'Jovan',
        'Šušić',
        true);