INSERT INTO machines (id, name, is_active)
VALUES (nextval('machine_id_seq'),
        'Buld.Cat D6',
        true),
       (nextval('machine_id_seq'),
        'Valjak HAM',
        true),
       (nextval('machine_id_seq'),
        'Man 15',
        true),
       (nextval('machine_id_seq'),
        'Man 16',
        true),
       (nextval('machine_id_seq'),
        'Cat grejder',
        true),
       (nextval('machine_id_seq'),
        'Dresta',
        true);