INSERT INTO overburden_reports (id,
                                report_date,
                                description,
                                note)
VALUES (nextval('overburden_report_id_seq'),
        '2026-05-01',
        'Dnevni izveštaj o otkopu - Odeljak A',
        'Normalan radni dan'),
       (nextval('overburden_report_id_seq'),
        '2026-05-02',
        'Dnevni izveštaj o otkopu - Odeljak B',
        'Blago kašnjenje zbog vremenskih uslova'),
       (nextval('overburden_report_id_seq'),
        '2026-05-03',
        'Dnevni izveštaj o otkopu - Odeljak C',
        'Visoka produktivnost u smeni'),
       (nextval('overburden_report_id_seq'),
        '2026-05-04',
        'Dnevni izveštaj o otkopu - Odeljak A',
        'Smanjena dostupnost mašina'),
       (nextval('overburden_report_id_seq'),
        '2026-05-05',
        'Dnevni izveštaj o otkopu - Odeljak B',
        'Uobičajen rad bez zastoja'),
       (nextval('overburden_report_id_seq'),
        '2026-05-06',
        'Dnevni izveštaj o otkopu - Odeljak C',
        'Dan sa velikim opterećenjem');